"""Initial schema.

Revision ID: 0001
Revises:
"""
from __future__ import annotations

from alembic import op

from app.db import Base
from app import models  # noqa: F401  (registers the tables on Base.metadata)

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # The schema is created from the SQLAlchemy metadata rather than transcribed
    # into op.create_table() calls. Two of the indexes here are *partial*
    # (uq_credentials_active_value and uq_attendance_one_member_meal_per_period)
    # and their predicates differ by dialect; letting SQLAlchemy emit the DDL
    # keeps them correct on Postgres in production and on SQLite under pytest,
    # and guarantees this revision cannot drift from models.py.
    #
    # Later revisions should be ordinary hand-written or autogenerated ones.
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
